// <auto-generated />
using System;
using ForgeERP.Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgeERP.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260524173851_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgeERP.Inventory.Domain.Stock.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityReserved")
                        .HasColumnType("numeric");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("StockBalances", "inventory");
                });

            modelBuilder.Entity("ForgeERP.Inventory.Domain.Stock.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StockBalanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StockBalanceId");

                    b.ToTable("StockMovements", "inventory");
                });

            modelBuilder.Entity("ForgeERP.Inventory.Domain.Stock.StockMovement", b =>
                {
                    b.HasOne("ForgeERP.Inventory.Domain.Stock.StockBalance", null)
                        .WithMany("StockMovements")
                        .HasForeignKey("StockBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeERP.Inventory.Domain.Stock.StockBalance", b =>
                {
                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
